export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "secondary-container": "#1a62fe",
        "surface-container-high": "#e5e9ed",
        "on-primary": "#ffffff",
        "inverse-surface": "#2c3134",
        "primary-container": "#0b2545",
        "inverse-primary": "#b1c7f0",
        "surface-container-low": "#f0f4f8",
        "on-primary-fixed": "#001c3b",
        "tertiary-fixed-dim": "#ffba20",
        "secondary-fixed": "#dce1ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b1c7f0",
        "surface-variant": "#dfe3e7",
        "primary": "#001026",
        "error": "#ba1a1a",
        "on-secondary-container": "#f3f3ff",
        "on-primary-fixed-variant": "#314769",
        "secondary": "#004ad1",
        "outline": "#74777f",
        "on-secondary-fixed-variant": "#003cac",
        "on-tertiary-fixed": "#271900",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdea8",
        "on-secondary": "#ffffff",
        "background": "#f6fafe",
        "primary-fixed": "#d5e3ff",
        "surface-dim": "#d7dade",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#332200",
        "surface-container": "#eaeef2",
        "surface": "#f6fafe",
        "surface-tint": "#495f82",
        "on-surface-variant": "#44474e",
        "outline-variant": "#c4c6cf",
        "secondary-fixed-dim": "#b5c4ff",
        "tertiary": "#180e00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#b78300",
        "on-tertiary-fixed-variant": "#5e4200",
        "surface-container-highest": "#dfe3e7",
        "on-secondary-fixed": "#00164d",
        "on-primary-container": "#778db2",
        "on-background": "#181c1f",
        "on-surface": "#181c1f",
        "inverse-on-surface": "#edf1f5",
        "surface-bright": "#f6fafe"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "gutter-lg": "2rem",
        "gutter-sm": "1rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "margin-sm": "1rem",
        "margin": "2rem",
        "space-md": "1rem",
        "margin-lg": "3rem"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-hero": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display-hero-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
};
