<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907120357 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deliverables (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, file_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A74C3A9166D1F9C ON deliverables (project_id)');
        $this->addSql('CREATE TABLE milestones (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_18F78184166D1F9C ON milestones (project_id)');
        $this->addSql('CREATE TABLE project_members (project_id INT NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (project_id, user_id))');
        $this->addSql('CREATE INDEX IDX_D3BEDE9A166D1F9C ON project_members (project_id)');
        $this->addSql('CREATE INDEX IDX_D3BEDE9AA76ED395 ON project_members (user_id)');
        $this->addSql('ALTER TABLE deliverables ADD CONSTRAINT FK_1A74C3A9166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE milestones ADD CONSTRAINT FK_18F78184166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9A166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projects ADD priority VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE projects ADD budget DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE projects ADD progress INT NOT NULL');
        $this->addSql('ALTER TABLE projects ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE projects ADD opportunity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE projects ADD manager_id UUID NOT NULL');
        $this->addSql('ALTER TABLE projects ALTER start_date DROP NOT NULL');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A49A34590F FOREIGN KEY (opportunity_id) REFERENCES opportunities (id)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4783E3463 FOREIGN KEY (manager_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A49A34590F ON projects (opportunity_id)');
        $this->addSql('CREATE INDEX IDX_5C93B3A4783E3463 ON projects (manager_id)');
        $this->addSql('ALTER TABLE tasks ADD progress INT NOT NULL');
        $this->addSql('ALTER TABLE tasks ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deliverables DROP CONSTRAINT FK_1A74C3A9166D1F9C');
        $this->addSql('ALTER TABLE milestones DROP CONSTRAINT FK_18F78184166D1F9C');
        $this->addSql('ALTER TABLE project_members DROP CONSTRAINT FK_D3BEDE9A166D1F9C');
        $this->addSql('ALTER TABLE project_members DROP CONSTRAINT FK_D3BEDE9AA76ED395');
        $this->addSql('DROP TABLE deliverables');
        $this->addSql('DROP TABLE milestones');
        $this->addSql('DROP TABLE project_members');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A49A34590F');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4783E3463');
        $this->addSql('DROP INDEX UNIQ_5C93B3A49A34590F');
        $this->addSql('DROP INDEX IDX_5C93B3A4783E3463');
        $this->addSql('ALTER TABLE projects DROP priority');
        $this->addSql('ALTER TABLE projects DROP budget');
        $this->addSql('ALTER TABLE projects DROP progress');
        $this->addSql('ALTER TABLE projects DROP updated_at');
        $this->addSql('ALTER TABLE projects DROP opportunity_id');
        $this->addSql('ALTER TABLE projects DROP manager_id');
        $this->addSql('ALTER TABLE projects ALTER start_date SET NOT NULL');
        $this->addSql('ALTER TABLE tasks DROP progress');
        $this->addSql('ALTER TABLE tasks DROP updated_at');
    }
}
