<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * CRM : les relances et la date de closing prévue.
 *
 * - reminders                    : le « à faire » du commercial, avec échéance et statut.
 *                                 Distinct de `activities`, qui ne garde que le « fait ».
 * - opportunities.expected_close_date : sans elle, une colonne « échéance » du pipeline est vide.
 *
 * SQL repris de `doctrine:schema:update --dump-sql`, afin d'être exactement
 * en accord avec le mapping des entités.
 */
final class Version20260927120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'CRM : table des relances et date de closing prévue sur les opportunités';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE reminders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(10) NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT DEFAULT NULL, opportunity_id INT DEFAULT NULL, assigned_to_id UUID DEFAULT NULL, created_by_id UUID NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX IDX_6D92B9D49395C3F3 ON reminders (customer_id)');
        $this->addSql('CREATE INDEX IDX_6D92B9D49A34590F ON reminders (opportunity_id)');
        $this->addSql('CREATE INDEX IDX_6D92B9D4F4BD7827 ON reminders (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_6D92B9D4B03A8386 ON reminders (created_by_id)');

        // Les relances « en retard » se trient par statut puis échéance :
        // sans cet index, la requête du matin du commercial scanne toute la table.
        $this->addSql('CREATE INDEX idx_reminder_due ON reminders (status, due_at)');

        $this->addSql('ALTER TABLE reminders ADD CONSTRAINT FK_6D92B9D49395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reminders ADD CONSTRAINT FK_6D92B9D49A34590F FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reminders ADD CONSTRAINT FK_6D92B9D4F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reminders ADD CONSTRAINT FK_6D92B9D4B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE opportunities ADD expected_close_date DATE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE opportunities DROP expected_close_date');
        $this->addSql('DROP TABLE reminders');
    }
}
