<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260926061620 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "categories" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "document_favorites" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, document_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F6514854A76ED395 ON "document_favorites" (user_id)');
        $this->addSql('CREATE INDEX IDX_F6514854C33F7837 ON "document_favorites" (document_id)');
        $this->addSql('CREATE TABLE "document_versions" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_number VARCHAR(50) NOT NULL, file_path VARCHAR(255) NOT NULL, size INT NOT NULL, checksum VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, created_by_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_961DB18BC33F7837 ON "document_versions" (document_id)');
        $this->addSql('CREATE INDEX IDX_961DB18BB03A8386 ON "document_versions" (created_by_id)');
        $this->addSql('CREATE TABLE document_tag (document_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (document_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_D0234567C33F7837 ON document_tag (document_id)');
        $this->addSql('CREATE INDEX IDX_D0234567BAD26311 ON document_tag (tag_id)');
        $this->addSql('CREATE TABLE "folders" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id INT DEFAULT NULL, owner_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE37D30F727ACA70 ON "folders" (parent_id)');
        $this->addSql('CREATE INDEX IDX_FE37D30F7E3C61F9 ON "folders" (owner_id)');
        $this->addSql('CREATE TABLE "tags" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE "document_favorites" ADD CONSTRAINT FK_F6514854A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "document_favorites" ADD CONSTRAINT FK_F6514854C33F7837 FOREIGN KEY (document_id) REFERENCES "documents" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "document_versions" ADD CONSTRAINT FK_961DB18BC33F7837 FOREIGN KEY (document_id) REFERENCES "documents" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "document_versions" ADD CONSTRAINT FK_961DB18BB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_tag ADD CONSTRAINT FK_D0234567C33F7837 FOREIGN KEY (document_id) REFERENCES "documents" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_tag ADD CONSTRAINT FK_D0234567BAD26311 FOREIGN KEY (tag_id) REFERENCES "tags" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE "folders" ADD CONSTRAINT FK_FE37D30F727ACA70 FOREIGN KEY (parent_id) REFERENCES "folders" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "folders" ADD CONSTRAINT FK_FE37D30F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE documents ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE documents DROP category');
        $this->addSql('ALTER TABLE documents DROP tags');
        $this->addSql('ALTER TABLE documents DROP folder');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B0728812469DE2 FOREIGN KEY (category_id) REFERENCES "categories" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B07288162CB942 FOREIGN KEY (folder_id) REFERENCES "folders" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A2B0728812469DE2 ON documents (category_id)');
        $this->addSql('CREATE INDEX IDX_A2B07288162CB942 ON documents (folder_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "document_favorites" DROP CONSTRAINT FK_F6514854A76ED395');
        $this->addSql('ALTER TABLE "document_favorites" DROP CONSTRAINT FK_F6514854C33F7837');
        $this->addSql('ALTER TABLE "document_versions" DROP CONSTRAINT FK_961DB18BC33F7837');
        $this->addSql('ALTER TABLE "document_versions" DROP CONSTRAINT FK_961DB18BB03A8386');
        $this->addSql('ALTER TABLE document_tag DROP CONSTRAINT FK_D0234567C33F7837');
        $this->addSql('ALTER TABLE document_tag DROP CONSTRAINT FK_D0234567BAD26311');
        $this->addSql('ALTER TABLE "folders" DROP CONSTRAINT FK_FE37D30F727ACA70');
        $this->addSql('ALTER TABLE "folders" DROP CONSTRAINT FK_FE37D30F7E3C61F9');
        $this->addSql('DROP TABLE "categories"');
        $this->addSql('DROP TABLE "document_favorites"');
        $this->addSql('DROP TABLE "document_versions"');
        $this->addSql('DROP TABLE document_tag');
        $this->addSql('DROP TABLE "folders"');
        $this->addSql('DROP TABLE "tags"');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B0728812469DE2');
        $this->addSql('ALTER TABLE "documents" DROP CONSTRAINT FK_A2B07288162CB942');
        $this->addSql('DROP INDEX IDX_A2B0728812469DE2');
        $this->addSql('DROP INDEX IDX_A2B07288162CB942');
        $this->addSql('ALTER TABLE "documents" ADD category VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "documents" ADD tags JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE "documents" ADD folder VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "documents" DROP category_id');
        $this->addSql('ALTER TABLE "documents" DROP folder_id');
    }
}
