<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905122531 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_requests (id UUID NOT NULL, requested_domain VARCHAR(100) NOT NULL, motivation TEXT NOT NULL, status VARCHAR(30) NOT NULL, rejection_reason TEXT DEFAULT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, assigned_role_id INT DEFAULT NULL, processed_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_16901760A76ED395 ON access_requests (user_id)');
        $this->addSql('CREATE INDEX IDX_16901760DC9B9A23 ON access_requests (assigned_role_id)');
        $this->addSql('CREATE INDEX IDX_169017602FFD4FD3 ON access_requests (processed_by_id)');
        $this->addSql('CREATE TABLE activities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(100) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT DEFAULT NULL, opportunity_id INT DEFAULT NULL, author_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B5F1AFE59395C3F3 ON activities (customer_id)');
        $this->addSql('CREATE INDEX IDX_B5F1AFE59A34590F ON activities (opportunity_id)');
        $this->addSql('CREATE INDEX IDX_B5F1AFE5F675F31B ON activities (author_id)');
        $this->addSql('CREATE TABLE api_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, scopes JSON NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CAD560EB3BC57DA ON api_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_2CAD560EA76ED395 ON api_tokens (user_id)');
        $this->addSql('CREATE TABLE course_sessions (id UUID NOT NULL, room VARCHAR(100) DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, course_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33D4F045591CC992 ON course_sessions (course_id)');
        $this->addSql('CREATE TABLE courses (id UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, teacher_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A9A55A4C41807E1D ON courses (teacher_id)');
        $this->addSql('CREATE TABLE customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, industry VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE equipments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, serial_number VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, purchased_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, assigned_to_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6F6C2544F4BD7827 ON equipments (assigned_to_id)');
        $this->addSql('CREATE TABLE grades (id UUID NOT NULL, score DOUBLE PRECISION NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id UUID NOT NULL, course_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE36110CB944F1A ON grades (student_id)');
        $this->addSql('CREATE INDEX IDX_3AE36110591CC992 ON grades (course_id)');
        $this->addSql('CREATE TABLE incidents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(50) NOT NULL, category VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reporter_id UUID NOT NULL, assignee_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E65135D0E1CFE6F5 ON incidents (reporter_id)');
        $this->addSql('CREATE INDEX IDX_E65135D059EC7D60 ON incidents (assignee_id)');
        $this->addSql('CREATE TABLE opportunities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) DEFAULT NULL, stage VARCHAR(50) NOT NULL, probability INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_406D4DB09395C3F3 ON opportunities (customer_id)');
        $this->addSql('CREATE TABLE permissions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, module VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DEDCC6F77153098 ON permissions (code)');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, customer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C93B3A49395C3F3 ON projects (customer_id)');
        $this->addSql('CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, is_system BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC777153098 ON roles (code)');
        $this->addSql('CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_1FBA94E6D60322AC ON role_permissions (role_id)');
        $this->addSql('CREATE INDEX IDX_1FBA94E6FED90CCA ON role_permissions (permission_id)');
        $this->addSql('CREATE TABLE tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(50) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, assignee_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50586597166D1F9C ON tasks (project_id)');
        $this->addSql('CREATE INDEX IDX_5058659759EC7D60 ON tasks (assignee_id)');
        $this->addSql('CREATE TABLE user_permission_overrides (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_granted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, permission_id INT NOT NULL, granted_by_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_573A27E9A76ED395 ON user_permission_overrides (user_id)');
        $this->addSql('CREATE INDEX IDX_573A27E9FED90CCA ON user_permission_overrides (permission_id)');
        $this->addSql('CREATE INDEX IDX_573A27E93151C11F ON user_permission_overrides (granted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX user_permission_unique ON user_permission_overrides (user_id, permission_id)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(30) DEFAULT NULL, status VARCHAR(30) NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE user_roles (user_id UUID NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('ALTER TABLE access_requests ADD CONSTRAINT FK_16901760A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_requests ADD CONSTRAINT FK_16901760DC9B9A23 FOREIGN KEY (assigned_role_id) REFERENCES roles (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_requests ADD CONSTRAINT FK_169017602FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE59395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE59A34590F FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE5F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE api_tokens ADD CONSTRAINT FK_2CAD560EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE course_sessions ADD CONSTRAINT FK_33D4F045591CC992 FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE courses ADD CONSTRAINT FK_A9A55A4C41807E1D FOREIGN KEY (teacher_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipments ADD CONSTRAINT FK_6F6C2544F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110591CC992 FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incidents ADD CONSTRAINT FK_E65135D0E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incidents ADD CONSTRAINT FK_E65135D059EC7D60 FOREIGN KEY (assignee_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE opportunities ADD CONSTRAINT FK_406D4DB09395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A49395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id)');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_50586597166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_5058659759EC7D60 FOREIGN KEY (assignee_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE user_permission_overrides ADD CONSTRAINT FK_573A27E9A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_permission_overrides ADD CONSTRAINT FK_573A27E9FED90CCA FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_permission_overrides ADD CONSTRAINT FK_573A27E93151C11F FOREIGN KEY (granted_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE access_requests DROP CONSTRAINT FK_16901760A76ED395');
        $this->addSql('ALTER TABLE access_requests DROP CONSTRAINT FK_16901760DC9B9A23');
        $this->addSql('ALTER TABLE access_requests DROP CONSTRAINT FK_169017602FFD4FD3');
        $this->addSql('ALTER TABLE activities DROP CONSTRAINT FK_B5F1AFE59395C3F3');
        $this->addSql('ALTER TABLE activities DROP CONSTRAINT FK_B5F1AFE59A34590F');
        $this->addSql('ALTER TABLE activities DROP CONSTRAINT FK_B5F1AFE5F675F31B');
        $this->addSql('ALTER TABLE api_tokens DROP CONSTRAINT FK_2CAD560EA76ED395');
        $this->addSql('ALTER TABLE course_sessions DROP CONSTRAINT FK_33D4F045591CC992');
        $this->addSql('ALTER TABLE courses DROP CONSTRAINT FK_A9A55A4C41807E1D');
        $this->addSql('ALTER TABLE equipments DROP CONSTRAINT FK_6F6C2544F4BD7827');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110CB944F1A');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110591CC992');
        $this->addSql('ALTER TABLE incidents DROP CONSTRAINT FK_E65135D0E1CFE6F5');
        $this->addSql('ALTER TABLE incidents DROP CONSTRAINT FK_E65135D059EC7D60');
        $this->addSql('ALTER TABLE opportunities DROP CONSTRAINT FK_406D4DB09395C3F3');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A49395C3F3');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6D60322AC');
        $this->addSql('ALTER TABLE role_permissions DROP CONSTRAINT FK_1FBA94E6FED90CCA');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_50586597166D1F9C');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_5058659759EC7D60');
        $this->addSql('ALTER TABLE user_permission_overrides DROP CONSTRAINT FK_573A27E9A76ED395');
        $this->addSql('ALTER TABLE user_permission_overrides DROP CONSTRAINT FK_573A27E9FED90CCA');
        $this->addSql('ALTER TABLE user_permission_overrides DROP CONSTRAINT FK_573A27E93151C11F');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('DROP TABLE access_requests');
        $this->addSql('DROP TABLE activities');
        $this->addSql('DROP TABLE api_tokens');
        $this->addSql('DROP TABLE course_sessions');
        $this->addSql('DROP TABLE courses');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE equipments');
        $this->addSql('DROP TABLE grades');
        $this->addSql('DROP TABLE incidents');
        $this->addSql('DROP TABLE opportunities');
        $this->addSql('DROP TABLE permissions');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE role_permissions');
        $this->addSql('DROP TABLE tasks');
        $this->addSql('DROP TABLE user_permission_overrides');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_roles');
    }
}
